### PR TITLE
Add nginx configuration

### PR DESCRIPTION
**Pull request by NyCodeGHG**
This PR adds a configuration file for nginx. The history mode routing is not working correctly without this configuration. Every non-index route would be a 404 without this config.

### CODE REVIEW

**Review by Androz2091 — COMMENTED** [review]
All right, thank you for your PR, if we start adding multiple files for the docker configuration, it would be nice to create a `docker` folder, with everything related to docker.

**Comment by Androz2091** [comment]
I'm not a regular docker user so I don't know what are the standards to store these files in a GH repository. Maybe I'm wrong and we should keep everything at root

**Comment by NyCodeGHG** [comment]
Should i move the nginx.conf file into a docker folder? The Dockerfile should stay at the root. When it's in a subdir, it's a little bit more difficult to build correctly.

**Comment by NyCodeGHG** [comment]
I don't think there is really a "standard". Most repos have their Dockerfiles in the root and if there are config files, most of the time there in the root or in a config directory. But thats up to you.

**Review by Androz2091 — APPROVED** [review]
LGTM thank you for your contribution

**Pull request merged**
