### PR TITLE
Added list of project contributors.

### PR DESCRIPTION
**Pull request by vanishedvan**
The website now shows a list of all project contributors at the bottom of the page.

### CODE REVIEW

**Comment by vanishedvan** [comment]
Looks like there have been commits while I was working on this feature, do you want me to make another pull request with the new feature/s?

**Comment by vanishedvan** [comment]
I still need an update on this, @Androz2091

**Comment by vanishedvan** [comment]
image

**Comment by vanishedvan** [comment]
image

**Comment by Androz2091** [comment]
I saw your PR and will review it as soon as possible 👍

**Comment by vanishedvan** [comment]
Ok, thanks!

**Comment by vanishedvan** [comment]
Fixed conflicts with the master branch.

**Review by Androz2091 — APPROVED** [review]
Thank you, this has been implemented in a65b350b2a9e1b92b55da985c6ea82567d88baa9

**Comment by vanishedvan** [comment]
👍

**Pull request closed without merging**
