### PR TITLE
Add default avatar

### PR DESCRIPTION
**Pull request by vanishedvan**
The website now displays the default Discord avatar if the Discord avatar cannot be fetched.

### CODE REVIEW

**Comment by vanishedvan** [comment]
image

**Review by Androz2091 — CHANGES_REQUESTED** [review]
I think that a better idea would be to fetch the user using https://diswho.androz2091.fr (from the ID in the extractor file, there is a `fetchUser` function). So the user info are up to date

**Comment by vanishedvan** [comment]
Ok, will do that.

**Comment by Androz2091** [comment]
All right otherwise I can do it

**Comment by vanishedvan** [comment]
I have done that, I just have to polish everything.

**Comment by vanishedvan** [comment]
@Androz2091 I have made the changes you requested. I am also applying the fetched username and discriminator, in case it gets changed.

**Comment by vanishedvan** [comment]
I have kept the default avatar, in case the server is down for some reason.

**Comment by vanishedvan** [comment]
@Androz2091 Can you give me some feedback on the changes if you are not busy?

**Review by Androz2091 — APPROVED** [review]
Thank you! 👍

**Pull request merged**
