### PR TITLE
Discord's new branding

### PR DESCRIPTION
**Pull request by LunaNiermann**
Discord updated its branding. The old blurple which was used for the text needs to be updated with the new blurple. 
The logo needs some updating as well.

https://discord.com/brand-new/branding

### CODE REVIEW

**Comment by Androz2091** [comment]
Maybe it's because I'm used to it, but I find the current colors more readdable on the website. Maybe we could change the background color?

Capture d’écran 2021-05-13 à 18 53 13
Capture d’écran 2021-05-13 à 18 53 08

**Comment by LasseNiermann** [comment]
On the website, they don't list the current background color anymore (but it's still used).
The background could be changed to complete black but idk.

**Comment by Androz2091** [comment]
> The new branding just looks weird imo. This tool could also just keep the old design (for now)

Yes, maybe. Please let this opened, and if someone has something to say about that, send it here.

**Comment by legendofmiracles** [comment]
Discord seems to be reverting their branding, the homepage has the old font, style and logo again.

**Comment by MZPL** [comment]
Many people dislike new blurple. It also seems like Discord doesn't want to admit they've made a mistake; otherwise, it wouldn't make any sense to me to revert changes only on their site but not in the app.
Comparing both screenshots above, I find old blurple more friendly. I don't think the change is really necessary for now.

**Comment by pro-gamer007** [comment]
I personally like the old blurple better than the new blurple and I'm sure a lot of other people have the same opinion as well...

**Comment by TheCreativeGod** [comment]
Can't this be made with a toggle?

(With background change as well for better view)

**Review by Androz2091 — CHANGES_REQUESTED** [review]
Please make this a toggle if you really want to see this change in the app. Thank you for your contribution, though :+1:

**Pull request closed without merging**
